# Generated by Django 5.1.15 on 2026-08-07 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_account_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="النص")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه مكتب",
                "verbose_name_plural": "تنبيهات المكاتب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "ntype",
                    models.CharField(
                        choices=[
                            ("txn_new", "حركة جديدة"),
                            ("txn_accepted", "قبول حركة"),
                            ("txn_rejected", "رفض حركة"),
                            ("txn_paid", "قبض حركة"),
                            ("txn_reversed", "عكس/تعديل حركة"),
                            ("settlement", "اعتماد/سحب"),
                            ("reconciliation", "مطابقة"),
                            ("limit", "الحد السالب"),
                            ("subscription", "اشتراك"),
                            ("broadcast", "تنبيه"),
                        ],
                        max_length=24,
                        verbose_name="النوع",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "body",
                    models.CharField(blank=True, max_length=500, verbose_name="النص"),
                ),
                (
                    "entity",
                    models.CharField(blank=True, max_length=64, verbose_name="الكيان"),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, max_length=64, verbose_name="معرّفه"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    )
                ],
            },
        ),
    ]
