# Generated by Django 5.1.15 on 2026-08-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="ntype",
            field=models.CharField(
                choices=[
                    ("txn_new", "حركة جديدة"),
                    ("txn_accepted", "قبول حركة"),
                    ("txn_rejected", "رفض حركة"),
                    ("txn_paid", "قبض حركة"),
                    ("txn_delivered", "تسليم حركة"),
                    ("txn_reversed", "عكس/تعديل حركة"),
                    ("settlement", "اعتماد/سحب"),
                    ("reconciliation", "مطابقة"),
                    ("limit", "الحد السالب"),
                    ("subscription", "اشتراك"),
                    ("broadcast", "تنبيه"),
                ],
                max_length=24,
                verbose_name="النوع",
            ),
        ),
    ]
