# Generated by Django 5.1.15 on 2026-08-07 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_account_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "chat_id",
                    models.CharField(max_length=100, verbose_name="معرّف المحادثة"),
                ),
                ("text", models.TextField(verbose_name="النص")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الإرسال"),
                            ("sent", "أُرسلت"),
                            ("failed", "فشلت"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="محاولات"),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="آخر خطأ"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أُرسلت في"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="لمجموعة المكتب",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة واتساب",
                "verbose_name_plural": "رسائل الواتساب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "bot_enabled",
                    models.BooleanField(default=False, verbose_name="البوت مفعّل"),
                ),
                (
                    "gateway_url",
                    models.URLField(blank=True, verbose_name="عنوان البوابة"),
                ),
                (
                    "gateway_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="رمز البوابة"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات واتساب",
                "verbose_name_plural": "إعدادات واتساب",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="uniq_wa_settings_per_tenant"
                    )
                ],
            },
        ),
    ]
