# Generated by Django 5.1.15 on 2026-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsettings",
            name="linked_number",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="الرقم المربوط"
            ),
        ),
    ]
