# Generated by Django 5.1.15 on 2026-08-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="الكود الفريد"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "مستأجر (مكتب كبير)",
                "verbose_name_plural": "المستأجرون (المكاتب الكبيرة)",
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("transaction", "حركة (حوالة)"),
                            ("settlement", "تسوية (اعتماد/سحب/دفعة)"),
                            ("reversal", "عكس قيد"),
                            ("manual", "يدوي"),
                        ],
                        max_length=20,
                        verbose_name="نوع القيد",
                    ),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=255, verbose_name="البيان"),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="core.journalentry",
                        verbose_name="يعكس القيد",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد يومية",
                "verbose_name_plural": "قيود اليومية",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("action", models.CharField(max_length=64, verbose_name="الفعل")),
                ("entity", models.CharField(max_length=64, verbose_name="الكيان")),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="معرّف الكيان"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الفاعل",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("small_office", "حساب مكتب صغير"),
                            ("intermediary_box", "صندوق وسيط مالي"),
                            ("shop_cash", "صندوق المحل (نقد)"),
                            ("self", "الحساب الذاتي للمكتب الكبير"),
                            ("fees_profit", "أرباح الأجور"),
                        ],
                        max_length=32,
                        verbose_name="النوع",
                    ),
                ),
                ("currency", models.CharField(max_length=8, verbose_name="العملة")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب",
                "verbose_name_plural": "الحسابات",
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="مدين"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="دائن"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="core.account",
                        verbose_name="الحساب",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="core.journalentry",
                        verbose_name="القيد",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطر قيد",
                "verbose_name_plural": "أسطر القيود",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("debit__gte", 0),
                            ("credit__gte", 0),
                            models.Q(("credit", 0), ("debit", 0), _negated=True),
                        ),
                        name="line_nonnegative_and_nonzero",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name", "kind", "currency"),
                name="uniq_account_per_tenant",
            ),
        ),
    ]
