# Generated by Django 5.1.15 on 2026-08-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "free_mode",
                    models.BooleanField(default=True, verbose_name="الوضع المجاني"),
                ),
                (
                    "self_registration_enabled",
                    models.BooleanField(
                        default=False, verbose_name="التسجيل الذاتي مفعّل"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المنصة",
                "verbose_name_plural": "إعدادات المنصة",
            },
        ),
    ]
