# Generated by Django 5.1.15 on 2026-08-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_platformsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[
                    ("small_office", "حساب مكتب صغير"),
                    ("intermediary_box", "صندوق وسيط مالي"),
                    ("shop_cash", "صندوق المحل (نقد)"),
                    ("self", "الحساب الذاتي للمكتب الكبير"),
                    ("fees_profit", "أرباح الأجور"),
                    ("fx_clearing", "مقاصة صرف العملات"),
                ],
                max_length=32,
                verbose_name="النوع",
            ),
        ),
    ]
