# Generated by Django 5.1.15 on 2026-08-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_account_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="allow_small_reconciliation",
            field=models.BooleanField(
                default=False,
                verbose_name="السماح للمكاتب الصغيرة بتثبيت المطابقة وإرسالها",
            ),
        ),
    ]
