# Generated by Django 5.1.15 on 2026-08-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_allow_small_reconciliation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="allow_small_reconciliation",
        ),
    ]
