# Generated by Django 5.1.15 on 2026-08-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_allow_small_reconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="logo",
            field=models.TextField(blank=True, default="", verbose_name="لوغو المنصة"),
        ),
    ]
