# Generated by Django 5.1.15 on 2026-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_adjustment_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="waha_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="مفتاح خادم الواتساب",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="waha_url",
            field=models.URLField(
                blank=True, default="", verbose_name="عنوان خادم الواتساب (WAHA)"
            ),
        ),
    ]
