# Generated by Django 5.1.15 on 2026-08-07 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boxes", "0001_initial"),
        ("core", "0003_alter_account_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "reference_code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="الرقم المرجعي"
                    ),
                ),
                (
                    "sender",
                    models.CharField(max_length=150, verbose_name="اسم المرسِل"),
                ),
                (
                    "beneficiary",
                    models.CharField(max_length=150, verbose_name="اسم المستفيد"),
                ),
                (
                    "destination",
                    models.CharField(max_length=150, verbose_name="الوجهة"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        verbose_name="المبلغ (بالمقبوضة)",
                    ),
                ),
                (
                    "currency_received",
                    models.CharField(max_length=8, verbose_name="العملة المقبوضة"),
                ),
                (
                    "currency_delivered",
                    models.CharField(max_length=8, verbose_name="العملة المسلَّمة"),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "amount_delivered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="المبلغ المسلَّم",
                    ),
                ),
                (
                    "fee_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="رأس مال الأجور",
                    ),
                ),
                (
                    "fee_charged",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="الأجور المستحقة",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("accepted", "مقبولة"),
                            ("cancelled", "ملغية"),
                            ("reversed", "معكوسة"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="حالة القبول",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "غير مدفوعة"), ("paid", "مدفوعة")],
                        default="unpaid",
                        max_length=16,
                        verbose_name="حالة الدفع",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("not_delivered", "لم تُسلَّم"),
                            ("delivered", "تم التسليم"),
                        ],
                        default="not_delivered",
                        max_length=16,
                        verbose_name="حالة التسليم",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القبول"
                    ),
                ),
                (
                    "approval_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.journalentry",
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="boxes.intermediarybox",
                        verbose_name="صندوق الوسيط",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأها",
                    ),
                ),
                (
                    "payment_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة",
                "verbose_name_plural": "الحركات",
                "ordering": ["-created_at"],
            },
        ),
    ]
