# Generated by Django 5.1.15 on 2026-08-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="اسم المرسِل"
            ),
        ),
    ]
