# Generated by Django 5.1.15 on 2026-08-08 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxes", "0003_seed_default_currencies"),
        ("core", "0006_platform_logo"),
        ("transactions", "0002_sender_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference_code",
            field=models.CharField(max_length=40, verbose_name="الرقم المرجعي"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference_code"), name="uniq_reference_per_tenant"
            ),
        ),
    ]
