# Generated by Django 5.1.15 on 2026-08-07 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_platformsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("code", models.CharField(max_length=8, verbose_name="الرمز")),
                ("name", models.CharField(max_length=50, verbose_name="الاسم")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملة",
                "verbose_name_plural": "العملات",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="IntermediaryBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم الصندوق")),
                ("number", models.CharField(max_length=50, verbose_name="رقم الصندوق")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "currencies",
                    models.ManyToManyField(
                        related_name="boxes",
                        to="boxes.currency",
                        verbose_name="العملات المتاحة",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "صندوق وسيط",
                "verbose_name_plural": "صناديق الوسطاء",
            },
        ),
        migrations.CreateModel(
            name="BoxCurrencyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("currency", models.CharField(max_length=8, verbose_name="العملة")),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="box_link",
                        to="core.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currency_accounts",
                        to="boxes.intermediarybox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopCashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("currency", models.CharField(max_length=8, verbose_name="العملة")),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_cash_link",
                        to="core.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmallOfficeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("currency", models.CharField(max_length=8, verbose_name="العملة")),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="small_office_link",
                        to="core.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="office_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("currency", models.CharField(max_length=8, verbose_name="العملة")),
                (
                    "negative_limit",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        verbose_name="الحد السالب المسموح",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                        verbose_name="المستأجر",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_limits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المكتب الصغير",
                    ),
                ),
            ],
            options={
                "verbose_name": "حد سالب",
                "verbose_name_plural": "الحدود السالبة",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "currency"), name="uniq_limit_per_user_currency"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_currency_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="intermediarybox",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="uniq_box_number_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="boxcurrencyaccount",
            constraint=models.UniqueConstraint(
                fields=("box", "currency"), name="uniq_box_currency"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopcashaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "currency"), name="uniq_shop_cash_currency"
            ),
        ),
        migrations.AddConstraint(
            model_name="smallofficeaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "currency"), name="uniq_small_office_currency"
            ),
        ),
    ]
