# Generated by Django 5.1.15 on 2026-08-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_chat_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="معرّف مجموعة البوت"
            ),
        ),
    ]
