# Generated by Django 5.1.15 on 2026-08-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_whatsapp_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.TextField(
                blank=True, default="", verbose_name="صورة البروفايل"
            ),
        ),
    ]
