# Generated by Django 5.1.15 on 2026-08-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False, verbose_name="موقوف مؤقتاً"),
        ),
    ]
