# Generated by Django 5.1.15 on 2026-08-07 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_platformsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="الاسم"),
                ),
                (
                    "max_small_offices",
                    models.PositiveIntegerField(verbose_name="حد المكاتب الصغيرة"),
                ),
                (
                    "max_transactions",
                    models.PositiveIntegerField(verbose_name="حد الحركات"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="السعر"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=8, verbose_name="عملة السعر"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="المدة بالأيام"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="متاحة للطلب"),
                ),
            ],
            options={
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="AdminBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="النص")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أرسله",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه أدمن",
                "verbose_name_plural": "تنبيهات الأدمن",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار التفعيل"),
                            ("active", "مفعّل"),
                            ("expired", "منتهٍ"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الطلب"),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التفعيل"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="ملاحظة"),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فعّله",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="admin_panel.package",
                        verbose_name="الباقة",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="core.tenant",
                        verbose_name="المكتب الكبير",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك",
                "verbose_name_plural": "الاشتراكات",
                "ordering": ["-requested_at"],
            },
        ),
    ]
